MikeStarina/pnhd-studio

public/index.html
src/components/main-menu/main-menu.jsx
src/components/shop-page-components/card-item.module.css
src/components/shop-page-components/cards-block.module.css

- закрытие меню по клику на фон
- title эмодзи
- новая раскладка галлереи магазина

added some features

---

src/components/popupCallBack/popupCallBack.jsx
src/components/popupCallBack/popupCallBack.module.css
src/components/popupModel/popupModel.jsx
src/services/actions/utility-actions.jsx

Заменил действие мыши, и добавил действие на esc для popup

bagfix: change onCkick on onMouseDown and added esc close popup

---

package.json
src/components/main-menu/main-menu.jsx
src/components/main-menu/main-menu.module.css
src/components/printingFirstScreen/printingFirstScreen.module.css
src/pages/cart-page/cart-page.module.css
src/pages/shop-page/shop-page.module.css

1  Убрал горизонтальный скрол на мобильной версии.
2 Текст фильтра на устройствах apple сделал черным.
3 Поправил иконку закрытия окна на устройствах apple.
4 Текст в корзине "назад" на устройствах apple сделал черным.

bagfix: color button, icon button, horizon scroll on mobile screen

---

src/components/size-selection/size-selection.module.css
src/pages/cart-page/cart-page.jsx
src/pages/cart-page/cart-page.module.css
src/pages/constructor-page/constructor-page.jsx
src/pages/item-page/item-page.jsx
src/pages/item-page/item-page.module.css
src/services/reducers/cart-data-reducer.jsx

Поправил стили у компонента "выбор размера".
Поправил передачу размеров из еденицы товара в принт.

fixbag: styles, constructor

---

src/pages/cart-page/cart-page.jsx
src/services/actions/cart-actions.jsx
src/utils/constants.jsx

Нашел и исправил баг подсчета суммы доставки. Иногда получалось что стоимость доставки пропадала если несколько раз изменить город доставки или попасть на город в котором нет пунктов выдачи.
Поправил подсчет сумм позиций для объекта заказа. Теперь стоимость позиции и печати высчитывается из кол-ва заказанных вещей.
Добавил несколько новых строк в объект. Они нужны для удобства формирования данных для юкассы

испраление расчетов сумм для объекта заказа

---

src/pages/cart-page/cart-page.jsx
src/services/actions/cart-actions.jsx

Изменил визуал у дропдауна списка городов.
округлил цену на доставку

update cities dropdown and shippigTarif

---

src/pages/cart-page/cart-page.jsx

Откорректировал работу всплывающего окна

corrected popup

---

src/pages/cart-page/cart-page.jsx

Добавил placeholder для инпута на ввод города для доставки

добавил placeholder

---

src/pages/cart-page/cart-page.jsx

При выходе из cart, доставка обнуляется

delivery update

---

src/components/shipping-components/shipping-select.module.css
src/pages/cart-page/cart-page.module.css
src/pages/constructor-page/constructor-page.module.css

- Поправил возможность добавлять принты в конструкторе для Mozilla.
- Сделал динамическое изменение высоты дропдауна для выбора города доставки. 
- Немного поиграл со шрифтами на разрешениях ниже 600 пикселей для дропдауна. 
- Добавил пунктам дропдауна немного воздуха
Update:
- Добавил hover эффект для пунктов выбора города и выбора ПВЗ

visual fix

---

src/pages/cart-page/cart-page.jsx
src/services/actions/shipping-actions.jsx

Изменил работу проверки инпута

changed how the validation input works

---

src/pages/constructor-page/constructor-page.jsx
src/services/reducers/editor-reducer.jsx

Проблема отображения пред просмотра принта в корзине заказа, решена

fix: load preview

---

src/components/main-page-components/price-screen.jsx
src/components/printing-methods-components/printing-method-price.jsx

поправил открытие попапа по нажатию кнопки "есть свой?".
Кнопка находится на главной страница и страницах "виды печати"

фикс кнопки

---

src/components/main-page-components/first-screen.jsx
src/components/main-page-components/shop-gallery.jsx
src/components/shop-page-components/cards-block.jsx
src/components/shop-page-components/filter-select.jsx
src/components/shop-page-components/filter-select.module.css
src/pages/cart-page/cart-page.jsx
src/pages/shop-page/shop-page.jsx
src/pages/shop-page/shop-page.module.css

- Внес правки в текст на главной странице
- Добавил валюту в стоимость доставки
- Изменил поведение курсора над фильтрами
- Поправил высоту кнопок и шрифт фильтров
- Изменил работу дропдаунов у фильтров, теперь открытым может быть только 1 
- Поправил ссылки на конструктор, которые находятся на главной странице

различные мини фиксы

---

src/components/main-page-components/shop-gallery.jsx
src/components/shop-page-components/cards-block.jsx
src/pages/shop-page/shop-page.jsx
src/utils/utils.jsx

- переделал формирование адресное строки

Any mini fix

---

src/components/app/App.jsx
src/components/main-menu/fullscreen-menu.jsx
src/components/main-menu/fullscreen-menu.module.css
src/components/main-menu/main-menu.jsx
src/components/main-menu/main-menu.module.css
src/ui/Button/Button.jsx
src/ui/Button/Button.module.css

1 change button in fullscreen on the general UI button
2 added general UI button in the main-menu

refactor: added general component button; added  button in main menu

---

src/components/main-menu/fullscreen-menu.jsx
src/components/main-menu/main-menu.jsx

Изменил пункт меню "Конструктор" на "Каталог".
В декстопной и мобильной версии меню

Конструктор = Каталог

---

src/components/ProductContent/ProductContent.module.css
src/pages/constructor-page/constructor-page.jsx
src/pages/constructor-page/constructor-page.module.css
src/pages/constructor-page/print.jsx
src/ui/icons/square.jsx
src/ui/icons/squareCircle.jsx
src/ui/icons/wordT.jsx

added a new style for the page
added dash for workspace

refactor: added new styles

---

src/components/ProductContent/ProductContent.jsx
src/pages/constructor-page/constructor-page.jsx
src/pages/constructor-page/constructor-page.module.css

Changed logic of working state between saving in memory and adding to the constructor

refactor: changed fn addtoprint in product

---

src/pages/cart-page/cart-page.jsx
src/pages/main-page/main-page.jsx

I have rewritten the meta tag Google.
Deleted link from cart to constructor.

refactor: rewritten google meta tag; deleted link to constructor

---

src/components/main-page-components/shop-gallery.jsx

поправил ссылки на главной странице ведущие на категории товара

поправил ссылки на товар

---

src/pages/checkout/checkout.jsx
src/services/actions/cart-actions.jsx
src/utils/addToMemory.js

feature: added calc for insurance

---

src/utils/constants.jsx

feature: change link on bot
